CREATE TABLE USERS_LOG (
    id_log SERIAL PRIMARY KEY,
    userid INTEGER REFERENCES USERS(userid),
    data_acesso DATE NOT NULL DEFAULT CURRENT_DATE,
    hora_acesso TIME NOT NULL DEFAULT CURRENT_TIME
);
