create or replace trigger trg_update_faccao
BEFORE UPDATE OF NOME ON FACCAO
FOR EACH ROW
BEGIN
    UPDATE NACAO_FACCAO
    SET FACCAO = :NEW.NOME
    WHERE FACCAO = :OLD.NOME;

    UPDATE PARTICIPA
    SET FACCAO = :NEW.NOME
    WHERE FACCAO = :OLD.NOME;
END;
/

