-- Declaração de pacote utilitário
CREATE OR REPLACE PACKAGE PCT_UTILITARIO AS 
    E_ESTRELA_NAO_ENCONTRADA EXCEPTION;

    FUNCTION CALCULAR_DISTANCIA_ESTRELAS(  -- distância euclidiana
        P_ESTRELA1 ESTRELA.ID_ESTRELA%TYPE,
        P_ESTRELA2 ESTRELA.ID_ESTRELA%TYPE
    ) RETURN NUMBER;
END PCT_UTILITARIO;

/

-- Corpo do pacote utilitário
CREATE OR REPLACE PACKAGE BODY PCT_UTILITARIO AS
    -- Função que calcula a distância euclidiana entre duas estrelas
    FUNCTION CALCULAR_DISTANCIA_ESTRELAS(
        P_ESTRELA1 ESTRELA.ID_ESTRELA%TYPE,
        P_ESTRELA2 ESTRELA.ID_ESTRELA%TYPE
    ) RETURN NUMBER AS
        ESTRELA1 ESTRELA%ROWTYPE;
        ESTRELA2 ESTRELA%ROWTYPE;
    BEGIN
        -- Seleção das estrelas
        SELECT * INTO ESTRELA1 FROM ESTRELA WHERE ID_ESTRELA = P_ESTRELA1;
        SELECT * INTO ESTRELA2 FROM ESTRELA WHERE ID_ESTRELA = P_ESTRELA2;

        -- Retorno da distância euclidiana
        RETURN SQRT(
            POWER(ESTRELA1.X - ESTRELA2.X, 2) +
            POWER(ESTRELA1.Y - ESTRELA2.Y, 2) +
            POWER(ESTRELA1.Z - ESTRELA2.Z, 2)
        );
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE E_ESTRELA_NAO_ENCONTRADA;
    END CALCULAR_DISTANCIA_ESTRELAS;
END PCT_UTILITARIO;

/